# Generated by Django 6.0.7 on 2026-07-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANDOVER', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
