# Generated by Django 6.0.7 on 2026-07-24 05:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANDOVER', '0003_alter_service_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
