# Generated by Django 6.0.7 on 2026-08-17 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANDOVER', '0006_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='service_qty',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=10)),
                ('street1', models.CharField(max_length=150)),
                ('street2', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('country', models.CharField(default='India', max_length=150)),
                ('zipcode', models.CharField(max_length=10)),
                ('total_price', models.FloatField()),
                ('payment_mode', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('UPI', 'UPI'), ('Internet Banking', 'Internet Banking'), ('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card')], default='Cash On Delivery', max_length=150)),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('On Service', 'On Service'), ('Completed', 'Completed')], default='Pending', max_length=150)),
                ('message', models.TextField(null=True)),
                ('tracking_no', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HANDOVER.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HANDOVER.service')),
            ],
        ),
    ]
