# Generated by Django 6.0.7 on 2026-08-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANDOVER', '0007_alter_cart_service_qty_order_orderservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
