# Generated by Django 6.0.7 on 2026-08-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANDOVER', '0008_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
