# Generated by Django 6.0.7 on 2026-08-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANDOVER', '0009_alter_order_tracking_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_price',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.FloatField(default=''),
            preserve_default=False,
        ),
    ]
