# Generated by Django 6.0.7 on 2026-08-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HANDOVER', '0010_order_actual_price_order_gst_order_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
