# Generated by Django 6.0.7 on 2026-08-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANDOVER', '0011_remove_order_actual_price_remove_order_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='actual_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
