from datetime import datetime, timedelta
import random
from HANDOVER.models import Service, Category
from django.core.management.base import BaseCommand
from typing import Any

class Command(BaseCommand):
    def handle(self, *args:Any, **option: Any):

        services = [
    {
        "name": "Kitchen Deep Cleaning",
        "category": "Home Services",
        "description": "Professional cleaning of kitchen cabinets, chimney exterior, countertops, sink, tiles, stove, and shelves. Removes grease, stains, and dirt to leave your kitchen fresh, hygienic, and ready for daily cooking.",
        "image": "https://www.dirtblastercleaningservices.com/wp-content/uploads/2021/05/Deep-Cleaning-Services-Pune.jpg",
        "price": 1499,
        "duration": timedelta(hours=3),
        "created_at": datetime(2025, 9, 2),
    },
    {
        "name": "Bathroom Deep Cleaning",
        "category": "Home Services",
        "description": "Intensive bathroom cleaning including toilet, wash basin, shower area, mirrors, wall tiles, and floor scrubbing. Hard water stains, soap residue, and bacteria are removed using professional-grade cleaning solutions.",
        "image": "https://safaikaro.in/wp-content/uploads/2025/06/pexels-karolina-grabowska-4239067-1200x800.jpg",
        "price": 899,
        "duration": timedelta(hours=2),
        "created_at": datetime(2025, 9, 6),
    },
    {
        "name": "Sofa Cleaning",
        "category": "Home Services",
        "description": "Deep sofa cleaning using fabric-safe shampoo and vacuum extraction. Removes dust, allergens, stains, pet hair, and unpleasant odors while preserving the upholstery and extending the life of your furniture.",
        "image": "https://handy2home.com/assets/img/normal/about_2_1.jpg",
        "price": 799,
        "duration": timedelta(hours=2, minutes=30),
        "created_at": datetime(2025, 9, 10),
    },
    {
        "name": "Carpet Cleaning",
        "category": "Home Services",
        "description": "Professional carpet cleaning with vacuuming, stain treatment, shampooing, and drying. Restores freshness, removes embedded dust, allergens, and improves the appearance of carpets and rugs.",
        "image": "https://techsquadteam.com/assets/profile/blogimages/23495d6f7ba3e74fd6b47b0018e60ffa.png",
        "price": 999,
        "duration": timedelta(hours=3),
        "created_at": datetime(2026, 5, 15),
    },
    {
        "name": "AC Repair",
        "category": "Appliance Repair",
        "description": "Diagnosis and repair of all major air conditioner brands including cooling issues, gas leakage, compressor problems, water leakage, and electrical faults. Genuine spare parts are used whenever required.",
        "image": "https://techsquadteam.com/assets/profile/blogimages/f00ab4df455700aeb2ff86da0cb79fe2.png",
        "price": 599,
        "duration": timedelta(hours=1, minutes=30),
        "created_at": datetime(2026, 2, 20),
    },
    {
        "name": "AC Installation",
        "category": "Appliance Repair",
        "description": "Installation of split and window air conditioners with secure wall mounting, copper pipe fitting, electrical connection, testing, and performance verification to ensure efficient cooling.",
        "image": "https://trustworthyhomeservices.in/wp-content/uploads/2023/01/trustworthy-blog24.jpg",
        "price": 1499,
        "duration": timedelta(hours=3),
        "created_at": datetime(2026, 2, 20),
    },
    {
        "name": "Refrigerator Repair",
        "category": "Appliance Repair",
        "description": "Repair service for refrigerators including compressor issues, cooling failure, thermostat replacement, gas charging, and electrical troubleshooting performed by experienced technicians.",
        "image": "https://www.revampservice.com/web-assets/images/fridge-repair1.jpg",
        "price": 699,
        "duration": timedelta(hours=2),
        "created_at": datetime(2026, 2, 20),
    },
    {
        "name": "Washing Machine Repair",
        "category": "Appliance Repair",
        "description": "Repair and servicing for fully automatic and semi-automatic washing machines. Includes motor repair, drum issues, drainage problems, and control panel troubleshooting.",
        "image": "https://content.jdmagicbox.com/v2/comp/delhi/v6/011pxx11.xx11.091008140828.z4v6/catalogue/neelam-home-appliances-care-kilokri-delhi-washing-machine-repair-and-services-ifb-1b3g2md.jpg",
        "price": 649,
        "duration": timedelta(hours=2, minutes=30),
        "created_at": datetime(2025, 11, 3),
    },
    {
        "name": "Microwave Oven Repair",
        "category": "Appliance Repair",
        "description": "Repair of microwave ovens including heating problems, keypad malfunction, fuse replacement, magnetron inspection, and safety testing before delivery.",
        "image": "https://repairdoctor.in/wp-content/uploads/2026/02/ifb-microwave-oven-repair-services-2.jpg",
        "price": 699,
        "duration": timedelta(hours=2),
        "created_at": datetime(2025, 11, 8),
    },
    {
        "name": "Fan Installation",
        "category": "Electrical Services",
        "description": "Professional installation of ceiling, wall, and exhaust fans with secure mounting, electrical wiring, regulator setup, and performance testing. Ensures safe operation and proper air circulation for residential and commercial spaces.",
        "image": "https://api.vijayhomesuperadmin.in/resubcat/1704970731121_decorative%20ceiling%20fan%20installation.jpg",
        "price": 399,
        "duration": timedelta(hours=1),
        "created_at": datetime(2026, 2, 12),
    },
    {
        "name": "Light Installation",
        "category": "Electrical Services",
        "description": "Installation of LED lights, chandeliers, decorative lights, outdoor lighting, and smart lighting systems. Includes wiring checks, fixture mounting, and complete safety testing before handover.",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp0IH9Nh09yh4ZHuL5DQ4pqBEQg0IbJBViqEOo2_8dvq_Rvet50PegN4nM&s=10",
        "price": 299,
        "duration": timedelta(minutes=45),
        "created_at": datetime(2025, 10, 16),
    },
    {
        "name": "Switch Board Repair",
        "category": "Electrical Services",
        "description": "Repair and replacement of damaged switches, sockets, MCBs, and switchboards. Electrical faults are diagnosed carefully and repaired using quality components to ensure safe and reliable usage.",
        "image": "https://5.imimg.com/data5/SELLER/Default/2026/4/602464244/VP/RL/EO/143959062/electrical-switch-board-repair-services.png",
        "price": 349,
        "duration": timedelta(hours=1),
        "created_at": datetime(2025, 11, 20),
    },
    {
        "name": "House Wiring",
        "category": "Electrical Services",
        "description": "Complete electrical wiring solutions for new houses, apartments, offices, and renovation projects. Includes concealed wiring, switch installation, distribution board setup, and safety inspection.",
        "image": "https://kgnelecticalandengineering.in/default/1759919411.webp",
        "price": 2499,
        "duration": timedelta(hours=8),
        "created_at": datetime(2025, 10, 24),
    },
    {
        "name": "Inverter Installation",
        "category": "Electrical Services",
        "description": "Installation of home inverter systems with battery connection, wiring, load balancing, and performance testing. Suitable for homes and small offices requiring reliable power backup.",
        "image": "https://aryaninverter.aaryanacrepair.in/wp-content/uploads/2026/01/Technician-reparing-inverter.jpg",
        "price": 899,
        "duration": timedelta(hours=2),
        "created_at": datetime(2026, 5, 28),
    },
    {
        "name": "Tap Installation",
        "category": "Plumbing",
        "description": "Installation and replacement of bathroom, kitchen, and outdoor taps with leak testing, water pressure adjustment, and secure fittings using durable plumbing accessories.",
        "image": "https://5.imimg.com/data5/PB/MW/MY-7343282/tap-repair-500x500.jpg",
        "price": 299,
        "duration": timedelta(minutes=45),
        "created_at": datetime(2026, 5, 1),
    },
    {
        "name": "Pipe Leak Repair",
        "category": "Plumbing",
        "description": "Professional repair of leaking water pipes, concealed pipelines, damaged joints, and broken fittings. The service includes leak detection, replacement of damaged sections, and pressure testing.",
        "image": "https://osicomfort.com/wp-content/uploads/2022/08/Plumbing.jpg",
        "price": 599,
        "duration": timedelta(hours=2),
        "created_at": datetime(2026, 1, 5),
    },
    {
        "name": "Drain Cleaning",
        "category": "Plumbing",
        "description": "Cleaning of blocked bathroom, kitchen, and outdoor drains using professional tools. Removes grease, soap deposits, food waste, and debris to restore smooth water flow.",
        "image": "https://www.woodbridgeplumbing.com/wp-content/uploads/2025/01/Untitled-design-1.jpg",
        "price": 499,
        "duration": timedelta(hours=1, minutes=30),
        "created_at": datetime(2026, 3, 8),
    },
    {
        "name": "Toilet Repair",
        "category": "Plumbing",
        "description": "Repair of flush tanks, toilet seats, pipelines, drainage systems, and water leakage issues. Includes replacement of faulty components and complete functionality testing.",
        "image": "https://kiddcoplumbing.com/wp-content/uploads/2022/03/toilet-plumbing.jpg",
        "price": 399,
        "duration": timedelta(hours=1, minutes=30),
        "created_at": datetime(2026, 6, 11),
    },
    {
        "name": "Water Heater Installation",
        "category": "Plumbing",
        "description": "Installation of electric and gas water heaters with proper plumbing connections, electrical safety checks, water leakage inspection, and operational testing.",
        "image": "https://westernrooter.com/wp-content/uploads/2024/05/worker-repairing-water-heater-scaled.jpg",
        "price": 799,
        "duration": timedelta(hours=2),
        "created_at": datetime(2026, 5, 14),
    },
    {
        "name": "Interior Painting",
        "category": "Painting",
        "description": "Professional interior painting service for homes and offices. Includes wall preparation, crack filling, primer application, premium paint coating, and complete cleanup after the work is finished. Suitable for apartments, villas, and commercial spaces.",
        "image": "https://sandiegohousepainting.com/wp-content/uploads/2025/11/Painting-Services-San-Diego.webp",
        "price": 4999,
        "duration": timedelta(days=1),
        "created_at": datetime(2026, 6, 18),
    },
    {
        "name": "Exterior Painting",
        "category": "Painting",
        "description": "Exterior wall painting using weather-resistant paints that protect buildings from rain, sunlight, and dust. Includes surface cleaning, crack repair, waterproof primer, and two coats of premium exterior paint.",
        "image": "https://carpentersomervillema.com/wp-content/uploads/2024/05/Exterior-Painting-Services-Somerville-MA.webp",
        "price": 6999,
        "duration": timedelta(days=2),
        "created_at": datetime(2026, 6, 18),
    },
    {
        "name": "Texture Painting",
        "category": "Painting",
        "description": "Decorative texture painting service that enhances walls with unique finishes and modern designs. Ideal for living rooms, bedrooms, offices, and feature walls to create an elegant appearance.",
        "image": "https://www.tejadecors.com/assets/img/service/texture-painting.webp",
        "price": 3499,
        "duration": timedelta(hours=8),
        "created_at": datetime(2026, 6, 18),
    },
    {
        "name": "Wallpaper Installation",
        "category": "Painting",
        "description": "Professional wallpaper installation service for residential and commercial interiors. Includes wall preparation, adhesive application, alignment, trimming, and finishing for a seamless look.",
        "image": "https://www.heilerpainting.com/wp-content/uploads/2024/02/wallpaper-hanging-installation-header.jpg",
        "price": 2499,
        "duration": timedelta(hours=5),
        "created_at": datetime(2026, 6, 18),
    },
    {
        "name": "Wood Polish",
        "category": "Painting",
        "description": "Wood polishing service for doors, windows, furniture, and cabinets. Restores shine, protects wooden surfaces, and enhances durability using high-quality polish and finishing materials.",
        "image": "https://colouredge.in/wp-content/uploads/2025/04/OIP-5.jpeg",
        "price": 1999,
        "duration": timedelta(hours=4),
        "created_at": datetime(2026, 6, 24),
    },

    {
        "name": "Door Repair",
        "category": "Carpentry",
        "description": "Repair service for wooden and metal doors including hinge replacement, lock fitting, alignment correction, handle replacement, and frame adjustments to restore smooth operation.",
        "image": "https://content.jdmagicbox.com/comp/def_content_category/pvc-door-repair-and-services/a69485af4f-pvc-door-repair-and-services-3-w2c80.jpg",
        "price": 599,
        "duration": timedelta(hours=2),
        "created_at": datetime(2026, 6, 26),
    },
    {
        "name": "Furniture Assembly",
        "category": "Carpentry",
        "description": "Assembly of beds, wardrobes, study tables, office desks, bookshelves, TV units, and modular furniture according to manufacturer specifications with secure fittings and finishing.",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCP2xk0fUr7Ipw6XhK-qfRwxiTcYj_IrwWloPo_bz1EwTXKeUcPqUo1Us&s=10",
        "price": 999,
        "duration": timedelta(hours=3),
        "created_at": datetime(2026, 6, 28),
    },
    {
        "name": "Cabinet Installation",
        "category": "Carpentry",
        "description": "Installation of kitchen cabinets, wardrobes, wall-mounted storage units, and office cabinets with precise measurements, secure mounting, and professional finishing.",
        "image": "https://hh.cabinetbasics.ca/wp-content/uploads/2024/06/Installation-scaled.jpg",
        "price": 1999,
        "duration": timedelta(hours=5),
        "created_at": datetime(2026, 6, 1),
    },
    {
        "name": "TV Unit Installation",
        "category": "Carpentry",
        "description": "Installation of wall-mounted TV units and entertainment cabinets with proper alignment, secure mounting, cable management, and finishing to complement your living space.",
        "image": "https://content.jdmagicbox.com/comp/def_content/led-tv-installation-services/led-tv-installation-services2-led-tv-installation-services-2-3fqj7.jpg",
        "price": 1499,
        "duration": timedelta(hours=4),
        "created_at": datetime(2026, 1, 4),
    },
    {
        "name": "Garden Maintenance",
        "category": "Gardening",
        "description": "Complete garden maintenance service including watering, pruning, fertilizing, weed removal, and seasonal plant care. Our professionals help keep your garden healthy, clean, and visually appealing throughout the year.",
        "image": "https://5.imimg.com/data5/SELLER/Default/2023/5/310550835/PC/IY/OS/152095378/garden-landscape-maintenance-service.jpeg",
        "price": 799,
        "duration": timedelta(hours=2),
        "created_at": datetime(2026, 1, 10),
    },
    {
        "name": "Lawn Mowing",
        "category": "Gardening",
        "description": "Professional lawn mowing service with edge trimming, grass collection, and cleanup. Suitable for residential gardens, villas, and commercial landscapes requiring regular maintenance.",
        "image": "https://d3fpcon17n0eur.cloudfront.net/lawn-mowing-guide-1.jpg",
        "price": 499,
        "duration": timedelta(hours=1, minutes=30),
        "created_at": datetime(2026, 1, 12),
    },
    {
        "name": "Plant Installation",
        "category": "Gardening",
        "description": "Selection and installation of indoor and outdoor plants with proper soil preparation and placement. Includes guidance on watering schedules and long-term plant care.",
        "image": "https://images.eu.ctfassets.net/8lnvtf96butm/5YfR4BjGy7TV3Uxa2ER0OB/31fdbc6a8ddf5dfcdc966fd7e503c4b8/Small_garden_design_3.jpg",
        "price": 999,
        "duration": timedelta(hours=2),
        "created_at": datetime(2026, 1, 15),
    },
    {
        "name": "Tree Trimming",
        "category": "Gardening",
        "description": "Safe trimming and pruning of trees to improve appearance, encourage healthy growth, and remove hazardous branches. Suitable for residential and commercial properties.",
        "image": "https://images.ctfassets.net/vwt5n1ljn95x/TZWxHeSCgplLaNrpzc9uX/5c094fcda4053b1fc19f20ededaa9814/Branch_Hedge_Trimming.jpeg?w=3840&q=75&fm=webp",
        "price": 1499,
        "duration": timedelta(hours=3),
        "created_at": datetime(2026, 1, 18),
    },
    {
        "name": "Laundry Service",
        "category": "Laundry",
        "description": "Doorstep laundry service with washing, drying, folding, and hygienic packaging. Suitable for everyday clothing, bedsheets, towels, and household fabrics.",
        "image": "https://www.mycleaners.in/images/1716359584.png",
        "price": 299,
        "duration": timedelta(days=1),
        "created_at": datetime(2026, 3, 24),
    },
    {
        "name": "Dry Cleaning",
        "category": "Laundry",
        "description": "Professional dry cleaning service for delicate garments including suits, sarees, coats, dresses, and premium fabrics using safe cleaning methods that preserve fabric quality.",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLLLxS_-Ar-rd9eU1feRmRtCsQsMPB0rWDrfD-_grOvBRnyP4ppi2rbMGI&s=10",
        "price": 399,
        "duration": timedelta(days=2),
        "created_at": datetime(2026, 3, 26),
    },
    {
        "name": "Steam Ironing",
        "category": "Laundry",
        "description": "Steam ironing service that removes wrinkles while protecting fabric quality. Suitable for office wear, uniforms, ethnic wear, and household garments.",
        "image": "https://thelaundrybasket.in/wp-content/uploads/2024/03/man-servant-doing-chores-around-house-1024x576.jpg",
        "price": 199,
        "duration": timedelta(hours=3),
        "created_at": datetime(2026, 3, 29),
    },
    {
        "name": "Curtain Cleaning",
        "category": "Laundry",
        "description": "Professional cleaning of curtains and drapes to remove dust, stains, allergens, and odors while maintaining fabric quality and color.",
        "image": "https://www.edchousekeepingservices.in/wp-content/uploads/2024/03/Curtains-Cleaning-Parde-Cleaning.jpg",
        "price": 699,
        "duration": timedelta(days=1),
        "created_at": datetime(2026, 3, 2),
    },
    {
        "name": "Shoe Cleaning",
        "category": "Laundry",
        "description": "Deep cleaning and polishing service for sports shoes, leather shoes, formal footwear, and sneakers using premium cleaning products and protective finishing.",
        "image": "https://laundryking.co.in/wp-content/uploads/2022/11/how-do-i-clean-my-shoes-nike-help-1024x683-1.webp",
        "price": 299,
        "duration": timedelta(hours=5),
        "created_at": datetime(2026, 6, 5),
    },

    {
        "name": "House Shifting",
        "category": "Moving & Shifting",
        "description": "Complete house shifting solution including packing, loading, transportation, unloading, and unpacking with trained professionals ensuring safe handling of belongings.",
        "image": "https://talalgoods.com/wp-content/uploads/2023/02/Best-Home-Shifting-Services-in-Islamabad.webp",
        "price": 6999,
        "duration": timedelta(days=1),
        "created_at": datetime(2026, 1, 1),
    },
    {
        "name": "Office Relocation",
        "category": "Moving & Shifting",
        "description": "Office relocation service with organized packing, secure transport of equipment, furniture handling, and quick setup to minimize business downtime.",
        "image": "https://bestructured.com/wp-content/uploads/2022/10/cardboard-box-with-folders-and.jpg",
        "price": 12999,
        "duration": timedelta(days=2),
        "created_at": datetime(2026, 1, 1),
    },
    {
        "name": "Furniture Transport",
        "category": "Moving & Shifting",
        "description": "Safe transportation of furniture including sofas, beds, wardrobes, dining tables, and office furniture using protective packing materials and experienced movers.",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsaajGEByFF4s-rT3kSOV1CTqgRaU1Bvdb9hfcpr5SXYQJ2dKYlUVUlkzf&s=10",
        "price": 2499,
        "duration": timedelta(hours=6),
        "created_at": datetime(2026, 1, 1),
    },
    {
        "name": "Packing Service",
        "category": "Moving & Shifting",
        "description": "Professional packing service using bubble wrap, cartons, foam sheets, and protective materials to ensure belongings remain safe during transportation or storage.",
        "image": "https://5.imimg.com/data5/DI/IA/MY-57118516/packing-service.png",
        "price": 1499,
        "duration": timedelta(hours=4),
        "created_at": datetime(2026, 1, 1),
    },

    {
        "name": "CCTV Installation",
        "category": "Security",
        "description": "Installation of CCTV surveillance systems for homes, apartments, offices, and commercial buildings. Includes camera setup, DVR/NVR configuration, mobile viewing, and testing.",
        "image": "https://5.imimg.com/data5/SELLER/Default/2024/6/425073469/ZD/HQ/EY/76756947/cctv-cameras-installation-service.jpg",
        "price": 3499,
        "duration": timedelta(hours=4),
        "created_at": datetime(2026, 1, 20),
    },
    {
        "name": "Smart Lock Installation",
        "category": "Security",
        "description": "Installation of smart door locks with fingerprint, PIN, RFID, and mobile app integration. Includes configuration, user setup, and security testing.",
        "image": "https://5.imimg.com/data5/SELLER/Default/2022/10/TA/VW/GF/147720649/door-bell-installation-service.jpg",
        "price": 2499,
        "duration": timedelta(hours=2),
        "created_at": datetime(2026, 1, 20),
    },
    {
        "name": "Video Door Phone Installation",
        "category": "Security",
        "description": "Installation of video door phone systems that allow homeowners to identify and communicate with visitors before granting access. Includes wiring, setup, and testing.",
        "image": "https://www.homeautomation.in/wp-content/uploads/2025/10/video-door-phone-1030x579.webp",
        "price": 3999,
        "duration": timedelta(hours=3),
        "created_at": datetime(2026, 1, 20),
    },
    {
        "name": "Alarm System Setup",
        "category": "Security",
        "description": "Setup of home and office security alarm systems with motion sensors, door sensors, sirens, and emergency alerts for enhanced safety and intrusion detection.",
        "image": "https://ftecindia.com/wp-content/uploads/2026/01/intrusion-alarm-system-installation-delhi-ncr.webp",
        "price": 2999,
        "duration": timedelta(hours=3),
        "created_at": datetime(2026, 1, 20),
    },
    {
        "name": "Fire Alarm Installation",
        "category": "Security",
        "description": "Installation of smoke detectors and fire alarm systems for residential and commercial properties. Includes sensor placement, control panel setup, and complete functionality testing.",
        "image": "https://5.imimg.com/data5/SELLER/Default/2024/1/373930215/SH/YH/BP/103570410/fire-alarm-system-maintenance-service-1.jpg",
        "price": 4499,
        "duration": timedelta(hours=4),
        "created_at": datetime(2026, 1, 20),
    }
]

        for service in services:
            Service.objects.create(
                name=service["name"],
                category=Category.objects.get(name=service["category"]),
                description=service["description"],
                image=service["image"],
                price=service["price"],
                duration=service["duration"],
                created_at=service["created_at"],
                rating = round(random.uniform(4.0, 5.0), 1),
                total_reviews = random.randint(10, 100),
                booking_count = random.randint(50, 500),
                discount_percentage = random.choice([0, 10, 15, 20, 25, 30])        
            )